### ISSUE TITLE
New entry submission

### ISSUE THREAD

**Issue by kcf-jackson** [matt-dray/awesome-r-games#13]
Hi, I want to submit an entry to the list under the puzzle section. 

- 1000 levels of Sokoban ([source](https://github.com/kcf-jackson/webr-animate/tree/jsonlite/examples/samples/sokoban), [app](https://webr-animate.netlify.app/?game=sokoban)) by [Jackson Kwok](https://github.com/kcf-jackson)

Thanks.

**Comment by matt-dray** [comment]
Excellent, many thanks!
