### ISSUE TITLE
Add Cactus Purge

### ISSUE THREAD

**Issue by weshinsley** [matt-dray/awesome-r-games#17]
Can I submit Cactus Purge - https://github.com/weshinsley/cactus.purge to your excellent list - it has 2 chapters so far of cactus-themed arcade action - chapter 1 is a version of Blitz, and chapter 2 is a sort of ski-ing/shooting combo. It works on all platforms in an ANSI-capable terminal window, and has sound effects....

More chapters will get added as the plot thickens....

**Comment by matt-dray** [comment]
Oh my word, this is utterly unhinged. And a perfect example of a game that belongs in this list! Please do contribute a PR. 🌵

**Comment by weshinsley** [comment]
PR #18 made with pleasure - hope it's ok and please edit as you feel!
