### ISSUE TITLE
Update outputs from one source, automatically

### ISSUE THREAD

**Issue by matt-dray** [matt-dray/awesome-r-games#4]
Maybe the data should be stored in a CSV or YAML or something. Then a GitHub Action can take that 'single point of truth' and update the static README and update the proposed webpage (#3).

**Comment by mcanouil** [comment]
There are guidelines to use the Awesome badge and create an "Awesome list".
Automated list are not allowed for instance, a table of contents has to be present, etc., see <https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md>.

Also, there is an open issue to let people know you are working on a new list (after checking it does not already exist): <https://github.com/sindresorhus/awesome/issues/2242>

**Comment by matt-dray** [comment]
Ah, thank you @mcanouil. Clearly I did not read anything. I'm pulling the badge/'awesome' references for now.

Re 'automated': not in the sense that items are gathered in an automated way, but in the sense that the existing items could be automatically read from this repo and added into an interactive table served with GitHub Pages so that people could filter the list, etc. But I don't think the list is ever going to be long enough that it's even worth having this alternate approach to viewing it.

**Comment by mcanouil** [comment]
> But I don't think the list is ever going to be long enough that it's even worth having this alternate approach to viewing it.

In that case and because of "_It's the result of hard work and the best I could possibly produce. If you have not put in considerable effort into your list, your pull request will be immediately closed._"  , I would recommend to simply do whatever you want outside of the "Awesome List" thing (which is referenced by GitHub, especially in the mobile app).

**Comment by matt-dray** [comment]
Yes, I think the biggest problem is that there probably aren't enough items to warrant a properly _curated_ list. I think probably it ends up as just a _list_. Thank you for highlighting this.

**Comment by matt-dray** [comment]
Closing because the repo has renamed away from 'awesome' and this has been acknowledged in the README.
