### ISSUE TITLE
Link CRAN packages to CRAN page

### ISSUE THREAD

**Issue by trickytank** [matt-dray/awesome-r-games#8]
Hi Matt, 

Should CRAN packages have a link to their CRAN page in the package name? Some games I added I don't know where their source or blogs are. Maybe there should be a marker for CRAN packages? (or a marker for non-CRAN packages?)

**Comment by matt-dray** [comment]
Thank you and yes, I agree, I think there's a few improvements that could be made here. Including CRAN/GitHub/web availability is a good start. I think another is a short sentence about what each game actually is/does (as per https://github.com/matt-dray/awesome-r-games/issues/9) would be good.
